Цель работы: реализовать базовый анализ датасета при помощи библиотеки panpas (Вывести весь датасет и описать его, вывести размерноть массива, вывести наименование всех колонок, вывести все уникальные значения, отсортировать по определенным параметрам, удалить ненужные столбцы или строчки, заменить определенные значения в датасете, удалить дубликаты, провести анализ с помощью функций info и describe, провести выборку данных по строкам и столбцам с помощью loc, сохранить новый датасет)

In [3]:
import pandas as pd

anime = pd.read_csv("anime.csv")

anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

Для начала нам необходимо прочитать csv фаил, записать его в переменную и вывести. После вывода мы можем увидеть все элементы, содержащиеся в нашем датасете

In [4]:
anime.shape

(12294, 7)

Далее необходимо узнать размерность нашего датасета с помощью функции shape. В нашем случае у нас 12294 строчки и 7 столбцов.

In [5]:
anime.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

После с помощью функции columns выведим названия всех столбцов. У нас столбы anime_id - просто какой-то айдишник, name - название аниме, genre - жанр аниме, type - тип аниме (что-то вроде фильм, сериал и т.п.), episodes - количество эпизодов, rating - рейтинг аниме на какой-то площадке, members - количество просмотров.

In [6]:
for col in anime:
    print(anime[col].unique())

[32281  5114 28977 ...  5621  6133 26081]
['Kimi no Na wa.' 'Fullmetal Alchemist: Brotherhood' 'Gintama°' ...
 'Violence Gekiga David no Hoshi'
 'Violence Gekiga Shin David no Hoshi: Inma Densetsu'
 'Yasuji no Pornorama: Yacchimae!!']
['Drama, Romance, School, Supernatural'
 'Action, Adventure, Drama, Fantasy, Magic, Military, Shounen'
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen' ...
 'Hentai, Sports' 'Drama, Romance, School, Yuri' 'Hentai, Slice of Life']
['Movie' 'TV' 'OVA' 'Special' 'Music' 'ONA' nan]
['1' '64' '51' '24' '10' '148' '110' '13' '201' '25' '22' '75' '4' '26'
 '12' '27' '43' '74' '37' '2' '11' '99' 'Unknown' '39' '101' '47' '50'
 '62' '33' '112' '23' '3' '94' '6' '8' '14' '7' '40' '15' '203' '77' '291'
 '120' '102' '96' '38' '79' '175' '103' '70' '153' '45' '5' '21' '63' '52'
 '28' '145' '36' '69' '60' '178' '114' '35' '61' '34' '109' '20' '9' '49'
 '366' '97' '48' '78' '358' '155' '104' '113' '54' '167' '161' '42' '142'
 '31' '373' '220' '46' '195' '17' '1787' '73' '147' '127' '16' '19' '98'
 '150' '76' '53' '124' '29' '115' '224' '44' '58' '93' '154' '92' '67'
 '172' '86' '30' '276' '59' '72' '330' '41' '105' '128' '137' '56' '55'
 '65' '243' '193' '18' '191' '180' '91' '192' '66' '182' '32' '164' '100'
 '296' '694' '95' '68' '117' '151' '130' '87' '170' '119' '84' '108' '156'
 '140' '331' '305' '300' '510' '200' '88' '1471' '526' '143' '726' '136'
 '1818' '237' '1428' '365' '163' '283' '71' '260' '199' '225' '312' '240'
 '1306' '1565' '773' '1274' '90' '475' '263' '83' '85' '1006' '80' '162'
 '132' '141' '125']
[ 9.37  9.26  9.25  9.17  9.16  9.15  9.13  9.11  9.1   9.06  9.05  9.04
  8.98  8.93  8.92  8.88  8.84  8.83  8.82  8.81  8.8   8.78  8.77  8.76
  8.75  8.74  8.73  8.72  8.71  8.69  8.68  8.67  8.66  8.65  8.64  8.62
  8.61  8.6   8.59  8.58  8.57  8.56  8.55  8.54  8.53  8.52  8.51  8.5
  8.49  8.48  8.47  8.46  8.45  8.44  8.43  8.42  8.41  8.4   8.39  8.38
  8.37  8.36  8.35  8.34  8.33  8.32  8.31  8.3   8.29  8.28  8.27  8.26
  8.25  8.24  8.23  8.22  8.21  8.2   8.19  8.18  8.17  8.16  8.15  8.14
  8.13  8.12  8.11  8.1   8.09  8.08  8.07  8.06  8.05  8.04  8.03  8.02
  8.01  8.    7.99  7.98  7.97  7.96  7.95  7.94  7.93  7.92  7.91  7.9
  7.89  7.88  7.87  7.86  7.85  7.84  7.83  7.82  7.81  7.8   7.79  7.78
  7.77  7.76  7.75  7.74  7.73  7.72  7.71  7.7   7.69  7.68  7.67  7.66
  7.65  7.64  7.63  7.62  7.61  7.6   7.59  7.58  7.57  7.56  7.55  7.54
  7.53  7.52  7.51  7.5   7.49  7.48  7.47  7.46  7.45  7.44  7.43  7.42
  7.41  7.4   7.39  7.38  7.37  7.36  7.35  7.34  7.33  7.32  7.31  7.3
  7.29  7.28  7.27  7.25  7.26  7.24  7.23  7.22  7.21  7.2   7.19  7.18
  7.17  7.16  7.14  7.15  7.13  7.12  7.11  7.1   7.09  7.08  7.07  7.06
  7.05  7.04  7.03  7.02  7.01  7.    6.99  6.98  6.97  6.96  6.95  6.94
  6.93  6.92  6.91  6.9   6.89  6.88  6.87  6.86  6.85  6.84  6.83  6.82
  6.81  6.8   6.79  6.78  6.75  6.77  6.76  6.74  6.73  6.72  6.71  6.7
  6.69  6.68  6.67  6.66  6.65  6.64  6.63  6.62  6.61  6.6   6.59  6.58
  6.57  6.56  6.55  6.54  6.53  6.52  6.51  6.47  6.5   6.49  6.48  6.46
  6.45  6.42  6.44  6.43  6.39  6.41  6.4   6.38  6.37  6.35  6.36  6.34
  6.33  6.32  6.31  6.3   6.29  6.28  6.27  6.26  6.25  6.22  6.24  6.23
  6.21  6.2   6.19  6.18  6.17  6.16  6.15  6.14  6.13  6.12  6.1   6.11
  6.09  6.08  6.06  6.07  6.05  6.04  6.03  6.01  6.02  6.    5.99  5.98
  5.97  5.96  5.95  5.94  5.93  5.92  5.91  5.89  5.9   5.88  5.87  5.86
  5.85  5.84  5.83  5.82  5.81  5.8   5.79  5.78  5.77  5.76  5.75  5.74
  5.73  5.72  5.7   5.71  5.69  5.68  5.67  5.66  5.65  5.64  5.63  5.62
  5.61  5.6   5.59  5.58  5.57  5.56  5.55  5.53  5.54  5.52  5.51  5.5
  5.49  5.48  5.46  5.47  5.45  5.44  5.43  5.42  5.41  5.4   5.39  5.38
  5.37  5.36  5.35  5.34  5.33  5.32  5.31  5.3   5.29  5.28  5.27  5.26
  5.24  5.25  5.23  5.22  5.21  5.2   5.19  5.14  5.18  5.17  5.16  5.15
  5.13  5.11  5.12  5.1   5.09  5.07  5.08  5.06  5.05  5.04  5.03  5.02
  5.01  5.    4.99  4.98  4.97  4.96  4.95  4.94  4.93  4.92  4.91  4.9
  4.89  4.88  4.84  4.87  4.86  4.85  4.83  4.82  4.81  4.8   4.79  4.78
  4.77  4.76  4.75  4.74  4.73  4.72  4.71  4.7   4.69  4.68  4.66  4.67
  4.65  4.64  4.63  4.62  4.6   4.59  4.58  4.57  4.56  4.55  4.54  4.53
  4.52  4.49  4.5   4.48  4.46  4.45  4.44  4.43  4.42  4.4   4.39  4.38
  4.36  4.35  4.34  4.32  4.31  4.3   4.28  4.27  4.26  4.25  4.24  4.23
  4.22  4.21  4.19  4.17  4.16  4.15  4.11  4.08  4.04  4.03  4.02  4.
  3.99  3.98  3.96  3.91  3.9   3.88  3.87  3.86  3.84  3.83  3.82  3.8
  3.78  3.76  3.75  3.74  3.73  3.71  3.7   3.68  3.65  3.63  3.62  3.6
  3.58  3.59  3.56  3.47  3.46  3.41  3.36  3.33  3.32  3.27  2.95  2.93
  2.78  2.67  2.37  2.14  2.    4.06  4.18  4.09  3.67  3.    4.33  3.89
  4.2   3.61  4.13  3.11  2.58  4.29  3.43  3.57  4.05  4.51  3.4   3.79
  3.81  3.92  3.48  3.38  3.95  4.61  3.34  3.02  2.69  3.5   3.97  3.85
   nan  3.77  3.53  9.33  4.14  4.12  3.2   3.93  3.52  2.55  9.    2.97
  4.1   3.39  3.17  9.5   3.25  2.8   2.91  2.75  4.41  3.72  3.94  1.67
  4.37  3.69  3.26  3.49  2.49  2.84  4.07  3.35  3.54  3.21  3.42  9.6
  3.28 10.    3.51  3.29  2.72  3.64  2.98  3.44  1.92  2.86  3.14]
[200630 793665 114262 ...  27411  57355    652]

Далее при помощи функции unique мы выведим все уникальные значения, содержащиеся в нашем датасете.

In [7]:
anime[anime["type"] == "TV"]

,anime_id,name,genre,type,episodes,rating,members
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
5,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351
...,...,...,...,...,...,...,...
11104,34522,"Wake Up, Girls! Shin Shou","Drama, Music",TV,Unknown,NaN,381
11106,34467,Yami Shibai 4th Season,"Dementia, Horror, Supernatural",TV,Unknown,NaN,1838
11107,32615,Youjo Senki,"Magic, Military",TV,Unknown,NaN,6652
11110,34284,Yuuki Yuuna wa Yuusha de Aru: Washio Sumi no Shou,"Drama, Fantasy, Magic, Slice of Life",TV,6,NaN,2593
11111,34445,Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou,"Drama, Fantasy, Magic, Slice of Life",TV,6,NaN,4439

При помощи данной команды мы можем отсортировать элементы датасета по определенному параметру и посмотреть все необходимые нам элементы.

In [8]:
anime = anime[anime["genre"] != "Hentai"]

anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12272,18197,Nudl Nude,"Comedy, Hentai, Parody",OVA,1,4.14,186
12273,18199,Nudl Nude 2,"Comedy, Hentai, Parody",OVA,1,4.00,146
12277,12397,Original Video Romance Animation,"Comedy, Hentai",OVA,2,4.66,176
12278,17833,Pink no Curtain,"Hentai, Slice of Life",OVA,1,3.61,138
12285,34399,Taimanin Asagi 3,"Demons, Hentai, Supernatural",OVA,Unknown,NaN,485

В данном случае мы перезапишем все элементы датасета кроме тех элементов с типом хентай. Тем самым мы удалим ненужные строчки.

In [9]:
import numpy as np
anime["rating"] = np.where(anime["rating"].isnull(), "not info", anime["rating"])

anime

C:\Users\n-tur\AppData\Local\Temp\ipykernel_14720\1007654999.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime["rating"] = np.where(anime["rating"].isnull(), "not info", anime["rating"])

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12272,18197,Nudl Nude,"Comedy, Hentai, Parody",OVA,1,4.14,186
12273,18199,Nudl Nude 2,"Comedy, Hentai, Parody",OVA,1,4.0,146
12277,12397,Original Video Romance Animation,"Comedy, Hentai",OVA,2,4.66,176
12278,17833,Pink no Curtain,"Hentai, Slice of Life",OVA,1,3.61,138
12285,34399,Taimanin Asagi 3,"Demons, Hentai, Supernatural",OVA,Unknown,not info,485

Здесь мы заменим значения NaN в с столбце рейтинга на not info

In [8]:
anime.drop_duplicates()

anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12272,18197,Nudl Nude,"Comedy, Hentai, Parody",OVA,1,4.14,186
12273,18199,Nudl Nude 2,"Comedy, Hentai, Parody",OVA,1,4.0,146
12277,12397,Original Video Romance Animation,"Comedy, Hentai",OVA,2,4.66,176
12278,17833,Pink no Curtain,"Hentai, Slice of Life",OVA,1,3.61,138
12285,34399,Taimanin Asagi 3,"Demons, Hentai, Supernatural",OVA,Unknown,not info,485

Тут мы удаляем все повторяющиеся элементы (которых у нас нет, но пункт должен быть :))

In [9]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11471 entries, 0 to 12285
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  11471 non-null  int64
 1   name      11471 non-null  object
 2   genre     11409 non-null  object
 3   type      11446 non-null  object
 4   episodes  11471 non-null  object
 5   rating    11471 non-null  object
 6   members   11471 non-null  int64
dtypes: int64(2), object(5)
memory usage: 716.9+ KB

После мы выведим подробную информацию о всех столбцах, в которой мы можем наблюдать, что столбцы anime_id и members имеют тип данных int, а все остальные object. Также не все столбцы заполнены значениями, есть те, у которых количество заполненых ячеек меньше чем количество столбцов.

In [10]:
anime.describe(include='all')

,anime_id,name,genre,type,episodes,rating,members
count,11471.000000,11471,11409,11446,11471,11471,1.147100e+04
unique,NaN,11469,3263,6,187,597,NaN
top,NaN,Shi Wan Ge Leng Xiaohua,Comedy,TV,1,not info,NaN
freq,NaN,2,523,3787,5427,223,NaN
mean,14275.196844,NaN,NaN,NaN,NaN,NaN,1.918948e+04
std,11524.734191,NaN,NaN,NaN,NaN,NaN,5.658436e+04
min,1.000000,NaN,NaN,NaN,NaN,NaN,5.000000e+00
25%,3435.500000,NaN,NaN,NaN,NaN,NaN,1.995000e+02
50%,10549.000000,NaN,NaN,NaN,NaN,NaN,1.477000e+03
75%,25115.000000,NaN,NaN,NaN,NaN,NaN,1.098700e+04
max,34527.000000,NaN,NaN,NaN,NaN,NaN,1.013917e+06

Далее с помощью функции describe выведим подробную статиску по нашему датасету (количество непустых ячеек, количество уникальных значений столбцов, самые часто встречающиеся значения, среднее арифметическое значение, стандартное отклонение и т.д.)

In [34]:
data = anime.loc[[1, 2, 11000, 5000, 7777, 5555], ["name", "type", "episodes", "rating"]]

data

,name,type,episodes,rating
1,Fullmetal Alchemist: Brotherhood,TV,64,9.26
2,Gintama°,TV,51,9.25
11000,Gyakusatsu Kikan,Movie,1,not info
5000,Neko Neko Fantasia,OVA,1,6.58
7777,A Play,Music,1,5.02
5555,Licca-chan Fushigi na Fushigi na Yunia Monogatari,OVA,2,6.42

Здесь мы выводим строки с конкретным номером (1, 2, 11000, 5000, 7777, 5555) и конкретные столбцы у этих строк (name, type, episodes, rating). И мы можем увидеть, что аниме под номером 1 - это Стальной алхимик: Братство, с типом TV, 64 эпизодами и рейтингом 9.26 (очень класная анимешка, советую посмотреть).

In [35]:
anime.to_csv("anime_new.csv", index=False)

После проведения всех работ над датасетом его необходимо записать в новый файлик и это можно сделать при помощи функции to_csv.

Вывод: выполнение практической работы №5 дало понятие как пользоваться библиотекой pandas, а также как при помощи данной библиотеки анализировать данные. В процессе работы был проанализирован датасет anime.csv (найдены размернось масива, наименование всех колок, все уникальные значения, элементы отсортироаны по определенному параметру, удалены ненужные столбцы и т.д.).